"""issue dict -> content/<edition>.js -> the existing web build.

The .js is the input format tools/build.js has always read (through
tools/strings/from-issue.js). Emitting it, rather than teaching build.js
about LaTeX, is what leaves the renderer and the newsproof signatures alone.
"""
import json
import subprocess
from pathlib import Path

HEADER = """\
/* GENERATED by tools/db-latex.py from content/{slug}.tex — do not edit.
   The .tex is the source of truth; run `python3 tools/db-latex.py build
   --edition {slug}` after changing it. Layout is not described here. */
"""


def emit_js(issue, slug):
    body = json.dumps(issue, ensure_ascii=False, indent=2)
    return HEADER.format(slug=slug) + "module.exports = " + body + ";\n"


def load_js(repo, path):
    """Read a content .js the way node does, so old hand-written files count."""
    script = "process.stdout.write(JSON.stringify(require(process.argv[1])))"
    out = subprocess.run(["node", "-e", script, str(Path(path).resolve())], cwd=repo,
                         check=True, capture_output=True, text=True).stdout
    return json.loads(out)


def build_site(repo):
    subprocess.run(["node", "tools/build.js"], cwd=repo, check=True)


def verify_proofs(repo):
    """The reader's badge check, offline: built pages must hash to the proofs."""
    return subprocess.run(["python3", "-m", "newsproof.check_live", "--offline"],
                          cwd=repo / "tools").returncode == 0


def diff_paths(a, b, path=""):
    """Structural diff of two issue dicts: a list of dotted paths that differ."""
    if isinstance(a, dict) and isinstance(b, dict):
        out = []
        for key in sorted(set(a) | set(b)):
            if key not in a or key not in b:
                out.append(f"{path}.{key} ({'missing' if key not in a else 'extra'})")
            else:
                out.extend(diff_paths(a[key], b[key], f"{path}.{key}"))
        return out
    if isinstance(a, list) and isinstance(b, list):
        if len(a) != len(b):
            return [f"{path} length {len(a)} != {len(b)}"]
        out = []
        for i, (x, y) in enumerate(zip(a, b)):
            out.extend(diff_paths(x, y, f"{path}[{i}]"))
        return out
    return [] if a == b else [f"{path}: {a!r} != {b!r}"]
