#!/usr/bin/env node
/* ============================================================================
   tools/check-site.js — read the built site back and complain

   `tools/build.js` writes 48 static pages (16 languages x 3 renderings) plus a
   sitemap, and nothing ever read them again. A missing key, a stray ampersand
   or a renamed anchor produced a page that looked fine in the terminal and was
   broken in a browser — the raw "&" in the comic credit shipped to fifteen
   pages that way. This reads the output the way a browser and a crawler would:

     LINKS      every internal href/src resolves to a file on disk, and every
                "#anchor" resolves to an id on the same page
     MARKUP     no raw "&", no duplicate ids, every <img> has alt, a <title>
     I18N       <html lang> matches the directory, RTL languages say so, and
                every page carries the full hreflang set + x-default, each
                pointing at a page that exists
     SITEMAP    the sitemap and the pages on disk are the same 48 URLs
     LANDMARKS  where a page has more than one <nav>, each one is named

   Usage:
     node tools/check-site.js          # check, exit 1 if anything is wrong
     node tools/check-site.js --list   # also print every page as it is checked

   Script bodies, style bodies and HTML comments are blanked before any of that
   runs -- see markupOnly() -- because a CSS comment or a JS string that happens
   to contain a tag or an href is neither a landmark nor a link.

   Run it after `node tools/build.js`. It has no dependencies on purpose: the
   rest of this repo installs nothing, and neither does this.
   ========================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.resolve(__dirname, '..');
const LIST = process.argv.includes('--list');

const ORIGIN = 'https://ourdailybre.ad';
const LANGS = ['en','fr','es','it','pl','la','zh-hans','zh-hant','pa','ko','ja','tl','vi','hi','ar','fa'];
const RTL = ['ar','fa'];
const VARIANTS = ['', 'lite', 'eink'];

/* The generated editions, as build.js lays them out. Anything else in the repo
   (studio.html, verify/) is a tool, not an edition, and is checked for markup
   but not for hreflang or sitemap membership. */
function editionPages() {
  const out = [];
  for (const lang of LANGS) for (const v of VARIANTS) {
    const dir = [lang === 'en' ? '' : lang, v].filter(Boolean).join('/');
    out.push({ lang, variant: v, dir, file: path.join(ROOT, dir, 'index.html'),
               url: ORIGIN + '/' + (dir ? dir + '/' : '') });
  }
  return out;
}
const EXTRA_PAGES = ['verify/index.html', 'studio.html'];

const problems = [];
const fail = (where, msg) => problems.push(`${where}: ${msg}`);

/* ── little parsers ────────────────────────────────────────────────────────
   Regex, not a DOM: the pages are machine-generated by one template, so the
   shapes are known and stable. Anything subtler than this belongs in a real
   validator, not in a repo that installs nothing. */
const attrs = (tag) => {
  const out = {};
  for (const m of tag.matchAll(/([a-zA-Z-]+)\s*=\s*"([^"]*)"/g)) out[m[1]] = m[2];
  return out;
};
const tagsOf = (html, name) =>
  [...html.matchAll(new RegExp(`<${name}\\b[^>]*>`, 'gi'))].map(m => m[0]);

/* Text outside of tags — where a bare "&" is a markup error. Inside an
   attribute an unescaped "&" is legal-ish and browsers cope, so this only
   looks at the text nodes, which is where it actually bites. */
/* Blank a run of characters, keeping its length and its newlines, so anything
   measured against the original string (an offset, a line number) still lands
   in the same place. */
const blank = (s) => s.replace(/[^\n]/g, ' ');

/* Everything below reads the page with regex rather than a DOM, which is fine
   for markup generated by one template -- but only if it is looking at markup.
   The bodies of <script> and <style>, and HTML comments, are text to a parser,
   not elements and not links, and reading them as markup invented 97 of the 145
   problems this file used to report:

     - style.css documents the rail as "a plain <nav> of in-page links", so
       every edition looked like it had a fourth, unnamed <nav> landmark;
     - the same comment cites the selector `a[href="#id"]`, so every edition
       looked like it had a dead anchor to an element with id="id";
     - studio.html builds a fetch URL as `a.href="/db-render/out/"+name`, so a
       runtime URL looked like a static href pointing at a missing directory.

   None of those is visible to a browser or a crawler. Blank them out first; the
   opening tags survive, so <script src> is still link-checked. */
function markupOnly(html) {
  return html
    .replace(/(<(script|style)\b[^>]*>)([\s\S]*?)(<\/\2\s*>)/gi,
             (_m, open, _name, body, close) => open + blank(body) + close)
    .replace(/<!--[\s\S]*?-->/g, blank);
}

function rawAmpersands(html) {
  const hits = [];
  const text = html.replace(/<[^>]*>/g, blank);
  for (const m of text.matchAll(/&(?!#\d+;|#x[0-9a-fA-F]+;|[a-zA-Z][a-zA-Z0-9]{1,31};)/g)) {
    const line = html.slice(0, m.index).split('\n').length;
    hits.push({ line, near: html.slice(Math.max(0, m.index - 40), m.index + 40).replace(/\s+/g, ' ') });
  }
  return hits;
}

function checkMarkup(rel, html) {
  if (!/<title>[^<]/i.test(html)) fail(rel, 'no <title>');
  if (!/<html[^>]*\blang="/i.test(html)) fail(rel, '<html> has no lang');

  for (const h of rawAmpersands(html))
    fail(rel, `raw "&" at line ${h.line} must be "&amp;" — …${h.near}…`);

  const ids = new Map();
  for (const m of html.matchAll(/\sid="([^"]+)"/g)) ids.set(m[1], (ids.get(m[1]) || 0) + 1);
  for (const [id, n] of ids) if (n > 1) fail(rel, `duplicate id #${id} (x${n})`);

  for (const tag of tagsOf(html, 'img'))
    if (!('alt' in attrs(tag))) fail(rel, `<img> without alt: ${tag.slice(0, 80)}`);

  // Where a page has more than one <nav>, a screen reader needs to tell them
  // apart; a single unnamed <nav> is fine.
  const navs = tagsOf(html, 'nav');
  if (navs.length > 1) {
    const names = [];
    for (const tag of navs) {
      const a = attrs(tag);
      const name = a['aria-label'] || a['aria-labelledby'];
      if (!name) fail(rel, `one of ${navs.length} <nav> landmarks has no accessible name: ${tag.slice(0, 60)}`);
      else if (names.includes(name)) fail(rel, `two <nav> landmarks share the name "${name}"`);
      else names.push(name);
    }
  }
  return ids;
}

function resolve(rel, from, target) {
  const clean = target.split('#')[0].split('?')[0];
  if (!clean) return null;
  let p = clean.startsWith('/') ? path.join(ROOT, clean) : path.resolve(path.dirname(from), clean);
  if (fs.existsSync(p) && fs.statSync(p).isDirectory()) p = path.join(p, 'index.html');
  else if (clean.endsWith('/')) p = path.join(p, 'index.html');
  return fs.existsSync(p) ? p : null;
}

function checkLinks(rel, file, html, ids) {
  const seen = new Set();
  for (const m of html.matchAll(/\b(href|src)="([^"]*)"/g)) {
    const url = m[2].trim();
    if (!url || seen.has(url)) continue;
    seen.add(url);
    if (/^(https?:)?\/\/|^(data|mailto|tel|javascript):/i.test(url)) continue;
    if (url.startsWith('#')) {
      const id = decodeURIComponent(url.slice(1));
      if (id && !ids.has(id)) fail(rel, `dead anchor ${url} — no element with that id`);
      continue;
    }
    if (!resolve(rel, file, url)) fail(rel, `dead ${m[1]} "${url}" — nothing on disk`);
  }
}

function checkI18n(page, html) {
  const rel = path.relative(ROOT, page.file);
  // Subtag case is not significant: the pages say "zh-Hans", the directory is
  // "zh-hans", and both are the same language tag.
  const lang = (html.match(/<html[^>]*\blang="([^"]+)"/i) || [])[1];
  if ((lang || '').toLowerCase() !== page.lang)
    fail(rel, `<html lang="${lang}"> but the page lives under /${page.dir || ''}`);
  const dir = (html.match(/<html[^>]*\bdir="([^"]+)"/i) || [])[1];
  const wantRtl = RTL.includes(page.lang);
  if (wantRtl && dir !== 'rtl') fail(rel, `${page.lang} is right-to-left but dir="${dir || ''}"`);
  if (!wantRtl && dir === 'rtl') fail(rel, `${page.lang} is not right-to-left but dir="rtl"`);

  const alts = new Map();
  for (const tag of tagsOf(html, 'link')) {
    const a = attrs(tag);
    // BCP-47 subtags are case-insensitive ("zh-Hans" is the conventional
    // spelling of "zh-hans"); compare in lower case so both are accepted.
    if (a.rel === 'alternate' && a.hreflang) alts.set(a.hreflang.toLowerCase(), a.href);
  }
  for (const l of LANGS) if (!alts.has(l)) fail(rel, `hreflang set is missing "${l}"`);
  if (!alts.has('x-default')) fail(rel, 'hreflang set is missing "x-default"');
  for (const [hl, href] of alts) {
    if (!href.startsWith(ORIGIN)) { fail(rel, `hreflang ${hl} points off-origin: ${href}`); continue; }
    const f = path.join(ROOT, href.slice(ORIGIN.length), 'index.html');
    if (!fs.existsSync(f)) fail(rel, `hreflang ${hl} -> ${href} which is not built`);
  }
  const canon = (html.match(/<link[^>]*\brel="canonical"[^>]*\bhref="([^"]+)"/i) || [])[1];
  if (!canon) fail(rel, 'no rel=canonical');
  else if (canon !== page.url) fail(rel, `canonical is ${canon}, expected ${page.url}`);
}

function checkSitemap(pages) {
  const f = path.join(ROOT, 'sitemap.xml');
  if (!fs.existsSync(f)) return fail('sitemap.xml', 'missing — run node tools/build.js');
  const xml = fs.readFileSync(f, 'utf8');
  const locs = [...xml.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m => m[1]);
  const want = new Set(pages.map(p => p.url));
  const got = new Set(locs);
  if (locs.length !== got.size) fail('sitemap.xml', `${locs.length} <loc> entries but only ${got.size} are distinct`);
  for (const u of want) if (!got.has(u)) fail('sitemap.xml', `does not list ${u}`);
  for (const u of got) if (!want.has(u)) fail('sitemap.xml', `lists ${u}, which build.js does not produce`);
}

/* ── run ──────────────────────────────────────────────────────────────────── */
const pages = editionPages();
let checked = 0;

for (const page of pages) {
  const rel = path.relative(ROOT, page.file);
  if (!fs.existsSync(page.file)) { fail(rel, 'not built — run node tools/build.js'); continue; }
  const html = markupOnly(fs.readFileSync(page.file, 'utf8'));
  if (LIST) console.log('  ' + rel);
  const ids = checkMarkup(rel, html);
  checkLinks(rel, page.file, html, ids);
  checkI18n(page, html);
  checked++;
}

for (const extra of EXTRA_PAGES) {
  const file = path.join(ROOT, extra);
  if (!fs.existsSync(file)) { fail(extra, 'missing'); continue; }
  const html = markupOnly(fs.readFileSync(file, 'utf8'));
  if (LIST) console.log('  ' + extra);
  const ids = checkMarkup(extra, html);
  checkLinks(extra, file, html, ids);
  checked++;
}

checkSitemap(pages);

console.log(`checked ${checked} page(s): ${pages.length} editions + ${EXTRA_PAGES.length} tool pages`);
if (!problems.length) {
  console.log('site check: clean');
  process.exit(0);
}
console.log(`\n${problems.length} problem(s):`);
const byFile = new Map();
for (const p of problems) {
  const [where, ...rest] = p.split(': ');
  if (!byFile.has(where)) byFile.set(where, []);
  byFile.get(where).push(rest.join(': '));
}
for (const [where, list] of byFile) {
  console.log(`  ${where}`);
  for (const m of list) console.log(`    - ${m}`);
}
process.exit(1);
